BEGIN;

-- ============================================================
-- SUPABASE SCHEMA - MG CLIMATIZAÇÃO
-- Criação e atualização idempotente, sem reset de dados.
-- Revise o projeto antes de executar manualmente no SQL Editor.
-- ============================================================

-- 1. TABELAS
CREATE TABLE IF NOT EXISTS public.services (
  id TEXT PRIMARY KEY,
  icon TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  bullet_points TEXT[] NOT NULL DEFAULT '{}',
  order_index INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.faq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  q TEXT NOT NULL,
  a TEXT NOT NULL,
  order_index INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'Cliente',
  text TEXT NOT NULL,
  rating INT DEFAULT 5,
  order_index INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  img TEXT NOT NULL,
  service_id TEXT REFERENCES public.services(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.before_after (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  before_img TEXT NOT NULL,
  after_img TEXT NOT NULL,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. VERIFICAÇÃO ADMINISTRATIVA
-- SECURITY DEFINER permite consultar admin_users sem expor a tabela.
-- A função não recebe parâmetros do cliente e nunca autoriza auth.uid() nulo.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    auth.uid() IS NOT NULL
    AND EXISTS (
      SELECT 1
      FROM public.admin_users
      WHERE user_id = auth.uid()
    ),
    false
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- 3. ROW LEVEL SECURITY
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faq ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.before_after ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- 4. REMOÇÃO IDempotente DE POLICIES ANTIGAS E ATUAIS
DROP POLICY IF EXISTS "Permitir leitura pública de servicos" ON public.services;
DROP POLICY IF EXISTS "Permitir escrita admin em servicos" ON public.services;
DROP POLICY IF EXISTS "Administradores gerenciam servicos" ON public.services;

DROP POLICY IF EXISTS "Permitir leitura pública de faq" ON public.faq;
DROP POLICY IF EXISTS "Permitir escrita admin em faq" ON public.faq;
DROP POLICY IF EXISTS "Administradores gerenciam faq" ON public.faq;

DROP POLICY IF EXISTS "Permitir leitura pública de depoimentos" ON public.testimonials;
DROP POLICY IF EXISTS "Permitir escrita admin em depoimentos" ON public.testimonials;
DROP POLICY IF EXISTS "Administradores gerenciam depoimentos" ON public.testimonials;

DROP POLICY IF EXISTS "Permitir leitura pública de portfolio" ON public.portfolio;
DROP POLICY IF EXISTS "Permitir escrita admin em portfolio" ON public.portfolio;
DROP POLICY IF EXISTS "Administradores gerenciam portfolio" ON public.portfolio;

DROP POLICY IF EXISTS "Permitir leitura pública de antes e depois" ON public.before_after;
DROP POLICY IF EXISTS "Permitir escrita admin em antes e depois" ON public.before_after;
DROP POLICY IF EXISTS "Administradores gerenciam antes e depois" ON public.before_after;

DROP POLICY IF EXISTS "Permitir leitura pública de configuracoes" ON public.settings;
DROP POLICY IF EXISTS "Permitir escrita admin em configuracoes" ON public.settings;
DROP POLICY IF EXISTS "Administradores gerenciam configuracoes" ON public.settings;

DROP POLICY IF EXISTS "Administradores leem o proprio acesso" ON public.admin_users;
DROP POLICY IF EXISTS "Permitir insercao em admin_users" ON public.admin_users;
DROP POLICY IF EXISTS "Apenas administradores gerenciam admin_users" ON public.admin_users;

-- 5. POLICIES DAS TABELAS PÚBLICAS
-- O site lê estes dados sem login. Toda escrita exige associação administrativa.
CREATE POLICY "Permitir leitura pública de servicos"
  ON public.services FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam servicos"
  ON public.services FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "Permitir leitura pública de faq"
  ON public.faq FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam faq"
  ON public.faq FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "Permitir leitura pública de depoimentos"
  ON public.testimonials FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam depoimentos"
  ON public.testimonials FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "Permitir leitura pública de portfolio"
  ON public.portfolio FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam portfolio"
  ON public.portfolio FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

CREATE POLICY "Permitir leitura pública de antes e depois"
  ON public.before_after FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam antes e depois"
  ON public.before_after FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

-- Leitura pública é necessária para configurações usadas pelo site sem login.
CREATE POLICY "Permitir leitura pública de configuracoes"
  ON public.settings FOR SELECT TO public USING (true);
CREATE POLICY "Administradores gerenciam configuracoes"
  ON public.settings FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

-- Usuário autenticado consulta, no máximo, a própria associação.
-- SECURITY DEFINER evita recursão ao verificar administradores já autorizados.
CREATE POLICY "Administradores leem o proprio acesso"
  ON public.admin_users FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id OR (SELECT public.is_admin()));

-- Somente um administrador previamente autorizado gerencia associações.
-- Um usuário comum não consegue inserir o próprio UUID nem se autoelevar.
CREATE POLICY "Apenas administradores gerenciam admin_users"
  ON public.admin_users FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

-- 6. SEEDS IDEMPOTENTES
INSERT INTO public.services (id, icon, title, description, bullet_points, order_index) VALUES
('servico-instalacao', 'Snowflake', 'Instalação de Ar-Condicionado', 'Instalação técnica completa seguindo as normas dos fabricantes, garantindo eficiência energética e durabilidade.', ARRAY['Infraestrutura e tubulação em cobre', 'Testes de estanqueidade e vácuo', 'Garantia de serviço e suporte'], 1),
('servico-higienizacao', 'Sparkles', 'Higienização e Limpeza Técnica', 'Limpeza profunda com bactericida e higienização de filtros, turbinas e bandejas de condensado.', ARRAY['Eliminação de fungos e bactérias', 'Melhora da qualidade do ar', 'Redução do consumo de energia'], 2),
('servico-manutencao', 'Wrench', 'Manutenção Preventiva e Corretiva', 'Diagnóstico preciso e reparo de vazamentos, substituição de peças e carga de gás refrigerante.', ARRAY['Carga de gás refrigerante R-410A / R-32', 'Troca de capacitores e placas', 'Diagnóstico e correção de ruídos'], 3),
('servico-pmoc', 'ShieldCheck', 'PMOC e Contrato Empresarial', 'Plano de Manutenção, Operação e Controle conforme exigência legal da ANVISA para empresas e comércios.', ARRAY['Laudo técnico e ART se necessário', 'Visitas periódicas programadas', 'Conformidade com normas sanitárias'], 4)
ON CONFLICT (id) DO NOTHING;

WITH faq_seed(q, a, order_index) AS (
  VALUES
    ('Quanto tempo demora uma instalação de ar-condicionado?', 'Em média, uma instalação residencial padrão leva de 2 a 4 horas, dependendo da complexidade da infraestrutura e do local de fixação das unidades.', 1),
    ('Com que frequência devo fazer a higienização do aparelho?', 'Para ambientes residenciais, recomendamos a higienização completa a cada 6 meses. Em escritórios ou comércios com uso intenso, o ideal é realizar a manutenção a cada 3 a 4 meses.', 2),
    ('Vocês atendem empresas e emitem nota fiscal?', 'Sim! Atendemos residências e empresas de todos os portes em Blumenau e região, com emissão de nota fiscal e contratos de manutenção PMOC.', 3),
    ('Como funciona a garantia do serviço de instalação?', 'Oferecemos garantia de 1 ano em nossos serviços de instalação, além de manter a garantia original do fabricante por seguir todos os padrões técnicos.', 4)
)
INSERT INTO public.faq (q, a, order_index)
SELECT seed.q, seed.a, seed.order_index
FROM faq_seed AS seed
WHERE NOT EXISTS (
  SELECT 1 FROM public.faq AS existing WHERE existing.q = seed.q
);

INSERT INTO public.settings (key, value) VALUES
('whatsapp_contact', '{"number": "5547997464218", "message": "Olá, MG Climatização! Gostaria de solicitar um orçamento para ar-condicionado."}'),
('budget_prices', '{"categories": {"instalacao": 350, "higienizacao": 180, "manutencao": 200, "recarga-gas": 220}}')
ON CONFLICT (key) DO NOTHING;

-- 7. BUCKET PÚBLICO DE IMAGENS
-- O bucket é criado público porque o site usa URLs públicas. Reexecuções não
-- sobrescrevem uma configuração existente e não modificam outros buckets.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'images',
  'images',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- 8. POLICIES DO STORAGE
DROP POLICY IF EXISTS "Leitura publica de imagens" ON storage.objects;
DROP POLICY IF EXISTS "Administradores enviam imagens" ON storage.objects;
DROP POLICY IF EXISTS "Administradores atualizam imagens" ON storage.objects;
DROP POLICY IF EXISTS "Administradores removem imagens" ON storage.objects;

CREATE POLICY "Leitura publica de imagens"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'images');

CREATE POLICY "Administradores enviam imagens"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'images' AND (SELECT public.is_admin()));

CREATE POLICY "Administradores atualizam imagens"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'images' AND (SELECT public.is_admin()))
  WITH CHECK (bucket_id = 'images' AND (SELECT public.is_admin()));

CREATE POLICY "Administradores removem imagens"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'images' AND (SELECT public.is_admin()));

-- 9. CONFIGURAÇÃO MANUAL DO PRIMEIRO ADMINISTRADOR
-- Este script não concede acesso administrativo automaticamente.
-- Um operador autorizado deve primeiro criar e conferir o usuário em
-- Authentication > Users. Depois, no SQL Editor do projeto correto, deve copiar
-- o UUID real e executar manualmente, após nova conferência:
--
-- INSERT INTO public.admin_users (user_id)
-- VALUES ('SUBSTITUA_PELO_UUID_REAL_DO_ADMIN');
--
-- Não descomente nem execute com um valor não verificado.

COMMIT;
